# CUDA 지원 Python 환경 사용
FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

# Python 설치
RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-venv pipenv && \
    rm -rf /var/lib/apt/lists/*

# 작업 디렉토리 설정
WORKDIR /app

# 코드 복사 및 의존성 설치
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

# 포트 노출 (8060)
EXPOSE 8060

# 실행 명령어 설정
CMD ["python3", "iopaint", "start", "--model", "Sanster/PowerPaint-V1-stable-diffusion-inpainting", "--device", "cuda", "--port", "8060", "--host=0.0.0.0", "--enable-remove-bg"]